name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --tag bnuri00/gitaction:latest .

    - name: Login to DokerHub
      run: docker login --u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}


    - name: Push the Docker image to the repository
      run: docker push bnuri00/gitaction:latest